/*
 * Copyright © 2022,2023,2024  James Crawford
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package io.jactl.compiler;

import io.jactl.Jactl;
import io.jactl.JactlContext;
import io.jactl.runtime.JactlObject;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Type;
import org.objectweb.asm.util.CheckClassAdapter;
import org.objectweb.asm.util.Printer;
import org.objectweb.asm.util.Textifier;
import org.objectweb.asm.util.TraceClassVisitor;

import java.io.PrintWriter;

import static org.objectweb.asm.Opcodes.ASM8;

public class JactlClassWriter extends ClassWriter {

  JactlContext context;
  String       internalJavaPackage;
  ClassVisitor cv;
  
  public JactlClassWriter(JactlContext context) {
    super(COMPUTE_MAXS + COMPUTE_FRAMES);
    this.context = context;
    this.internalJavaPackage = context.internalJavaPackage;
    init(context.debugLevel);
  }
  
  public JactlClassWriter(String internalJavaPackage) {
    this(internalJavaPackage, 0);
  }
  
  public JactlClassWriter(String internalJavaPackage, int debugLevel) {
    super(COMPUTE_MAXS + COMPUTE_FRAMES);
    this.internalJavaPackage = internalJavaPackage;
    init(debugLevel);
  }
  
  private void init(int debugLevel) {
    if (context != null && context.checkClasses()) {
      cv = new CheckClassAdapter(this);
    }
    if (debugLevel > 0) {
      Printer printer = new JactlTextifier();
      cv = new TraceClassVisitor(cv, printer, new PrintWriter(System.out) {
        { super.print(": "); }
        @Override
        public void print(String s) {
          super.print(s.replaceAll("\n", "\n: "));
        }
      });
    }
  }
  
  public ClassVisitor getClassVisitor() {
    return cv == null ? this : cv;
  }

  private static final String objectClass = Type.getInternalName(Object.class);

  @Override
  protected String getCommonSuperClass(String type1, String type2) {
    if (type1.equals(type2)) {
      return type1;
    }
    if (type1.equals(objectClass) || type2.equals(objectClass)) {
      return objectClass;
    }
    String jactlObjectClass = Type.getInternalName(JactlObject.class);
    if (type1.startsWith(internalJavaPackage) && type2.equals(jactlObjectClass)) {
      return jactlObjectClass;
    }
    if (type2.startsWith(internalJavaPackage) && type1.equals(jactlObjectClass)) {
      return jactlObjectClass;
    }
    try {
      ClassLoader classLoader = getClassLoader();
      if (type1.startsWith(internalJavaPackage) && type2.startsWith(internalJavaPackage)) {
//        ClassDescriptor clss1 = context.getClassDescriptor(type1);
//        ClassDescriptor clss2 = context.getClassDescriptor(type2);
//        Class clss1 = Class.forName(type1.replace('/', '.'), false, classLoader);
//        Class clss2 = Class.forName(type2.replace('/', '.'), false, classLoader);
        Class clss1 = JactlClassLoader.forName(type1.replace('/', '.'), false);
        Class clss2 = JactlClassLoader.forName(type2.replace('/', '.'), false);
        if (clss1.isAssignableFrom(clss2)) {
          return type1;
        }
        if (clss2.isAssignableFrom(clss1)) {
          return type2;
        }
        if (clss1.isInterface() || clss2.isInterface()) {
          return jactlObjectClass;
        }
        else {
          do {
            clss1 = clss1.getSuperclass();
          }
          while (clss1 != null && !clss1.isAssignableFrom(clss2));
          
          return clss1 == null ? jactlObjectClass : Type.getInternalName(clss1);
        }
      }
      else if (type1.startsWith(internalJavaPackage) || type2.startsWith(internalJavaPackage)) {
        // Common ancestor or Jactl class and non-Jactl class is Object, but I am not sure
        // if returning Object is the right answer or whether this is just hiding an issue
        // in the generated bytecode...
        return Type.getInternalName(Object.class);
      }
      return super.getCommonSuperClass(type1, type2);
    }
    catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Textifier that truncates long strings when outputing LDC instructions
   */
  private static class JactlTextifier extends Textifier {
    JactlTextifier() { super(ASM8); }
    @Override public void visitLdcInsn(Object v) {
      super.visitLdcInsn(v instanceof String && ((String) v).length() > 80 ? ((String) v).substring(0, 80) + " ..." : v);
    }
    @Override public Textifier visitMethod(int access, String name, String descriptor, String signature, String[] exceptions) {
      super.visitMethod(access, name, descriptor, signature, exceptions);
      Textifier textifier = new JactlTextifier();
      text.add(textifier.getText());
      return textifier;
    }
  }
}
