/*
 * Copyright 2022 James Crawford
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.jactl;

////////////////////////////////////////////////////////////////////
// File was generated using GenerateClasses.pl in tools directory
// DO NOT EDIT THIS FILE
////////////////////////////////////////////////////////////////////


import java.util.*;

import io.jactl.JactlType;
import io.jactl.Stmt;
import io.jactl.Utils;
import io.jactl.runtime.ClassDescriptor;
import io.jactl.runtime.SourceLocation;
import org.objectweb.asm.Label;
import org.objectweb.asm.Type;

import io.jactl.runtime.FunctionDescriptor;

import static io.jactl.JactlType.HEAPLOCAL;
import static io.jactl.TokenType.STAR;
import static io.jactl.TokenType.UNDERSCORE;

/**
 * Expr classes for our AST.
 */
public abstract class Expr extends JactlUserDataHolder {

  public abstract <T> T accept(Visitor<T> visitor);


  public Token      location;
  public JactlType  type;
  public JactlType  parentType = null;   // For use by Intellij plugin when needing to locate field within parent type
  public boolean    isResolved = false;

  public boolean    isConst = false;   // Whether expression consists only of constants
  public Object     constValue;        // If expression is only consts then we keep the
                                // result of evaluating the expression during the
                                // resolve phase here.

  public boolean    isCallee    = false; // Whether we are the callee in a call expression
  public boolean    couldBeNull = true;  // Whether result could be null
  public boolean    isAsync     = false; // Whether expression contains an async call

  // Flag that indicates whether result for the Expr is actually used. Most expressions
  // have their value used, for example, when nested within another expression or when
  // the expression is used as a condition for if/while/for or as assignment to a variable.
  // For some expressions (e.g. the top Expr in an expression statement) the result of the
  // expression is ignored so this flag allows us to know whether to leave the result on
  // the stack or not.
  public boolean isResultUsed = true;

  public boolean wasNested = false;      // Set if expression was inside parentheses.
                                  // So we can tell difference between "x = 1" and "(x) = [1]"

  // Marker interface to indicate whether MethodCompiler visitor for that element type
  // handles leaving result on stack or not (based on isResultUsed flag) or whether
  // result management needs to be done for it.
  public interface ManagesResult {}

  // Whether expression is a direct function call (and not a closure)
  public boolean isFunctionCall() {
    if (!(this instanceof Expr.Identifier)) { return false; }
    Identifier ident = (Expr.Identifier)this;
    return ident.varDecl.type.is(JactlType.FUNCTION) && ident.varDecl.funDecl != null;
  }

  // True if expression is a MapLiteral where all keys are string literals
  public boolean isConstMap() {
    return this instanceof Expr.MapLiteral && ((Expr.MapLiteral)this).literalKeyMap != null;
  }

  // True if expr is "null"
  public boolean isNull() {
    return this instanceof Expr.Literal && ((Expr.Literal)this).value.getType().is(TokenType.NULL);
  }

  // True if this is a "new X()" expression
  public boolean isNewInstance() {
    return this instanceof Expr.MethodCall && ((Expr.MethodCall)this).parent instanceof Expr.InvokeNew;
  }

  // True if expression is "super"
  public boolean isSuper() {
    return this instanceof Expr.Identifier && ((Expr.Identifier)this).identifier.getStringValue().equals(Utils.SUPER_VAR);
  }

  public boolean isThis() {
    return this instanceof Expr.Identifier && ((Expr.Identifier)this).identifier.getStringValue().equals(Utils.THIS_VAR);
  }

  // True if Literal or Identifier so does not require much code generation. Used in match expressions to
  // determine whether we can duplicate the code for the result when there are multiple patterns that give
  // the same result.
  public boolean isSimple() {
    return this instanceof Expr.Literal || this instanceof Expr.Identifier;
  }

  public boolean isLiteral() {
    return this instanceof Literal || this instanceof ListLiteral || this instanceof MapLiteral;
  }

  public boolean isStar() {
    return this instanceof Expr.Identifier && ((Expr.Identifier) this).identifier.is(STAR) ||
           this instanceof Expr.Literal && ((Expr.Literal) this).value.is(STAR);
  }

  public boolean isTypePattern() {
    return this instanceof Expr.TypeExpr || this instanceof Expr.ConstructorPattern || this instanceof Expr.VarDecl ||
           this instanceof Expr.Identifier && (((Expr.Identifier)this).identifier.is(UNDERSCORE) || ((Expr.Identifier)this).varDecl.isBindingVar);
  }

  public JactlType patternType() {
    return this instanceof Expr.TypeExpr ? ((Expr.TypeExpr) this).typeVal :
           this instanceof Expr.ConstructorPattern ? ((Expr.ConstructorPattern)this).typeExpr.typeVal :
           this.type;
  }

  public static class Binary extends Expr {
    public Expr  left;
    public Token operator;
    public Expr  right;
    public boolean createIfMissing = false;  // Used for field access used as lvalues
    public boolean isFieldAccess   = false;  // True if this is a field access expression where field name and type are known
    public Token originalOperator;           // When -- or ++ is turned into x = x + 1 this is the actual --/++ op
    public Binary(Expr left, Token operator, Expr right) {
      this.left = left;
      this.operator = operator;
      this.right = right;
      this.location = operator;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitBinary(this); }
    @Override public String toString() { return "Binary[" + "left=" + left + ", " + "operator=" + operator + ", " + "right=" + right + "]"; }
  }

  public static class RegexMatch extends Expr {
    public Expr    string;
    public Token   operator;
    public Expr    pattern;
    public String  modifiers;
    public boolean isSubstitute = false;
    public boolean implicitItMatch;   // True if standalone /regex/ which we then implicitly match against "it"
    public VarDecl captureArrVarDecl;
    public RegexMatch(Expr string, Token operator, Expr pattern, String modifiers, boolean implicitItMatch) {
      this.string = string;
      this.operator = operator;
      this.pattern = pattern;
      this.modifiers = modifiers;
      this.implicitItMatch = implicitItMatch;
      this.location = operator;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitRegexMatch(this); }
    @Override public String toString() { return "RegexMatch[" + "string=" + string + ", " + "operator=" + operator + ", " + "pattern=" + pattern + ", " + "modifiers=" + modifiers + ", " + "implicitItMatch=" + implicitItMatch + "]"; }
  }

  public static class RegexSubst extends RegexMatch {
    public Expr    replace;
    public boolean isComplexReplacement;   // True if replacement string has embedded expressions
    { isSubstitute = true; }
    public RegexSubst(Expr string, Token operator, Expr pattern, String modifiers, boolean implicitItMatch, Expr replace, boolean isComplexReplacement) {
      super(string, operator, pattern, modifiers, implicitItMatch);
      this.replace = replace;
      this.isComplexReplacement = isComplexReplacement;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitRegexSubst(this); }
    @Override public String toString() { return "RegexSubst[" + "string=" + string + ", " + "operator=" + operator + ", " + "pattern=" + pattern + ", " + "modifiers=" + modifiers + ", " + "implicitItMatch=" + implicitItMatch + ", " + "replace=" + replace + ", " + "isComplexReplacement=" + isComplexReplacement + "]"; }
  }

  /**
   * Ternary expression - only used for:
   *     cond ? trueExpr : falseExpr
   */
  public static class Ternary extends Expr {
    public Expr  first;
    public Token operator1;
    public Expr  second;
    public Token operator2;
    public Expr  third;
    public Ternary(Expr first, Token operator1, Expr second, Token operator2, Expr third) {
      this.first = first;
      this.operator1 = operator1;
      this.second = second;
      this.operator2 = operator2;
      this.third = third;
      this.location = operator1;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitTernary(this); }
    @Override public String toString() { return "Ternary[" + "first=" + first + ", " + "operator1=" + operator1 + ", " + "second=" + second + ", " + "operator2=" + operator2 + ", " + "third=" + third + "]"; }
  }

  public static class PrefixUnary extends Expr implements ManagesResult {
    public Token operator;
    public Expr  expr;
    public PrefixUnary(Token operator, Expr expr) {
      this.operator = operator;
      this.expr = expr;
      this.location = operator;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitPrefixUnary(this); }
    @Override public String toString() { return "PrefixUnary[" + "operator=" + operator + ", " + "expr=" + expr + "]"; }
  }

  public static class PostfixUnary extends Expr implements ManagesResult {
    public Expr  expr;
    public Token operator;
    public PostfixUnary(Expr expr, Token operator) {
      this.expr = expr;
      this.operator = operator;
      this.location = operator;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitPostfixUnary(this); }
    @Override public String toString() { return "PostfixUnary[" + "expr=" + expr + ", " + "operator=" + operator + "]"; }
  }

  public static class Cast extends Expr implements ManagesResult {
    public Token       token;
    public JactlType  castType;
    public Expr        expr;
    public Cast(Token token, JactlType castType, Expr expr) {
      this.token = token;
      this.castType = castType;
      this.expr = expr;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitCast(this); }
    @Override public String toString() { return "Cast[" + "token=" + token + ", " + "castType=" + castType + ", " + "expr=" + expr + "]"; }
  }

  public static class Call extends Expr {
    public Token      token;
    public Expr       callee;
    public List<Expr> args;

    public boolean validateArgsAtCompileTime; // true if we should validate args at compile time rather than at runtime

    // If we are a call to an arbitrary function/closure then it is possible that the
    // function we are calling returns an Iterator:  def f = x.map; f()
    // In this case we need to check that if the result is not immediately used as the
    // target of a chained method call (f().each()) and the result was an Iterator then
    // the result must be converted to a List.
    public boolean isMethodCallTarget;
    public Call(Token token, Expr callee, List<Expr> args) {
      this.token = token;
      this.callee = callee;
      this.args = args;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitCall(this); }
    @Override public String toString() { return "Call[" + "token=" + token + ", " + "callee=" + callee + ", " + "args=" + args + "]"; }
  }

  public static class MethodCall extends Expr {
    public Token          leftParen;
    public Expr           parent;
    public Token          accessOperator; // Either '.' or '?.'
    public String         methodName;     // Either the method name or field name that holds a MethodHandle
    public SourceLocation methodNameLocation;
    public Expr           methodNameExpr;  // Needed for Intellij plugin so we can attach parentType to it for "goto definition"
    public List<Expr> args;

    public FunctionDescriptor methodDescriptor;
    public boolean validateArgsAtCompileTime = true;   // true if we should validate args at compile time rather than at runtime

    // True if result of method call becomes the target of the next method call. This is used so
    // that we can allow Iterators to be the result of a list.map() call which is then itself used
    // as the target of another map() call (or call that can operator on an Iterator). Otherwise
    // we need to convert the Iterator into a List since Iterators don't really exist at the Jactl
    // language level and are only used as an implementation detail for some iteration methods.
    // E.g.: x.map().map().each()
    // This means that the x.map() can return an iterator that is then used in the next .map() which
    // returns another iterator that is used in the .each() call.
    // If the result is not to be used by another method then we convert the Iterator into a List.
    // That way x.map{} which in theory does nothing but might have side effects if the closure has
    // a side effect will still run and cause the side effects to happen even though the end result
    // is not actually used.
    public boolean isMethodCallTarget = false;
    public MethodCall(Token leftParen, Expr parent, Token accessOperator, String methodName, SourceLocation methodNameLocation, Expr methodNameExpr, List<Expr> args) {
      this.leftParen = leftParen;
      this.parent = parent;
      this.accessOperator = accessOperator;
      this.methodName = methodName;
      this.methodNameLocation = methodNameLocation;
      this.methodNameExpr = methodNameExpr;
      this.args = args;
      this.location = leftParen;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitMethodCall(this); }
    @Override public String toString() { return "MethodCall[" + "leftParen=" + leftParen + ", " + "parent=" + parent + ", " + "accessOperator=" + accessOperator + ", " + "methodName=" + methodName + ", " + "methodNameLocation=" + methodNameLocation + ", " + "methodNameExpr=" + methodNameExpr + ", " + "args=" + args + "]"; }
  }

  public static class Literal extends Expr {
    public Token   value;
    public boolean isField = false;   // True if literal uses as field name
    public Literal(Token value) {
      this.value = value;
      this.location = value;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitLiteral(this); }
    @Override public String toString() { return "Literal[" + "value=" + value + "]"; }
  }

  public static class ListLiteral extends Expr {
    public Token start;
    public List<Expr> exprs = new ArrayList<>();
    public ListLiteral(Token start) {
      this.start = start;
      this.location = start;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitListLiteral(this); }
    @Override public String toString() { return "ListLiteral[" + "start=" + start + "]"; }
  }

  public static class MapLiteral extends Expr {
    public Token start;
    public List<Pair<Expr,Expr>> entries = new ArrayList<>();
    public boolean               isNamedArgs;    // whether this map is used as named args for function/method/constructor call
    public Map<String,Expr>      literalKeyMap;  // Map based on key names if all keys were string literals
    public MapLiteral(Token start) {
      this.start = start;
      this.location = start;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitMapLiteral(this); }
    @Override public String toString() { return "MapLiteral[" + "start=" + start + "]"; }
  }

  public static class Identifier extends Expr {
    public Token              identifier;
    public Expr.VarDecl       varDecl;               // for variable references
    public boolean            couldBeFunctionCall = false;
    public boolean            firstTimeInPattern  = false;   // used in switch patterns to detect first use of a binding var
    public boolean            createIfMissing     = false;
    public boolean            createAsList        = false;
    public FunctionDescriptor  getFuncDescriptor() { return varDecl.funDecl.functionDescriptor; }
    public JactlUserDataHolder getDeclaration()    { return varDecl == null ? null : varDecl.originalVarDecl == null ? varDecl : varDecl.originalVarDecl; }
    public Identifier(Token identifier) {
      this.identifier = identifier;
      this.location = identifier;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitIdentifier(this); }
    @Override public String toString() { return "Identifier[" + "identifier=" + identifier + "]"; }
  }

  public static class ClassPath extends Expr {
    public Token pkg;
    public Token className;
    public String fullClassName() { return pkg.getStringValue() + "." + className.getStringValue(); }
    public ClassPath(Token pkg, Token className) {
      this.pkg = pkg;
      this.className = className;
      this.location = pkg;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitClassPath(this); }
    @Override public String toString() { return "ClassPath[" + "pkg=" + pkg + ", " + "className=" + className + "]"; }
  }

  public static class ExprString extends Expr {
    public Token exprStringStart;
    public List<Expr> exprList = new ArrayList<>();
    public ExprString(Token exprStringStart) {
      this.exprStringStart = exprStringStart;
      this.location = exprStringStart;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitExprString(this); }
    @Override public String toString() { return "ExprString[" + "exprStringStart=" + exprStringStart + "]"; }
  }

  /**
   * Variable declaration with optional initialiser.
   * This is done as an expression in case value of the assignment
   * is returned implicitly from a function/closure.
   */
  public static class VarDecl extends Expr implements ManagesResult {
    public Token           name;
    public Token           equals;
    public Expr            initialiser;
    public Expr.FunDecl    owner;               // Which function variable belongs to (for local vars)
    public boolean         isGlobal;            // Whether global (bindings var) or local
    public boolean         isHeapLocal;         // Is this a heap local var
    public boolean         isPassedAsHeapLocal; // If we are an explicit parameter and HeapLocal is passed to us from wrapper
    public boolean         isParam;             // True if variable is a parameter of function (explicit or implicit)
    public boolean         isExplicitParam;     // True if explicit declared parameter of function
    public boolean         isField;             // True if instance field of a class
    public boolean         isConstVar;          // True if declared as a constant
    public boolean         isBindingVar;        // True if this is a binding variable in a switch destructing pattern
    public int             slot = -1;           // Which local variable slot
    public int             nestingLevel;        // What level of nested function owns this variable (1 is top level)
    public Label           declLabel;           // Where variable comes into scope (for debugger)
    public Expr.FunDecl    funDecl;             // If type is FUNCTION then this is the function declaration
    public ClassDescriptor classDescriptor;     // If type is CLASS then this is the class descriptor
    public VarDecl         parentVarDecl;       // If this is a HeapLocal parameter then this is the VarDecl from parent
    public VarDecl         originalVarDecl;     // VarDecl for actual original variable declaration

    // If never reassigned we know it is effectively final. This means that if we have "def f = { ... }" and
    // closure is not async and f is never reassigned (isFinal == true) we know that calls to "f()" will never
    // be async.
    public boolean      isFinal = true;

    public JactlType    lastAssignedType;      // Track last type assigned for completions in Intellij plugin

    // When we are in the wrapper function we create a variable for every parameter.
    // This points to the parameter so we can turn it into HeapLocal if necessary and
    // to set its type (if it was declared as "var") once we know the type of the initialiser.
    public VarDecl      paramVarDecl;

    Type descriptorType() { return isPassedAsHeapLocal ? HEAPLOCAL.descriptorType() : type.descriptorType(); }
    public VarDecl(Token name, Token equals, Expr initialiser) {
      this.name = name;
      this.equals = equals;
      this.initialiser = initialiser;
      this.location = name;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitVarDecl(this); }
    @Override public String toString() { return "VarDecl[" + "name=" + name + ", " + "equals=" + equals + ", " + "initialiser=" + initialiser + "]"; }
  }

  /**
   * Function declaration
   * We make this an expression so we can have last statement in a block be a function declaration
   * and have it then returned as the return value of the function.
   */
  public static class FunDecl extends Expr implements ManagesResult {
    public Token              startToken;   // Either identifier for function decl or start brace for closure
    public Token              nameToken;    // Null for closures and script main
    public JactlType         returnType;
    public List<Stmt.VarDecl> parameters;
    public Stmt.Block         block;

    public FunctionDescriptor functionDescriptor;
    public Expr.VarDecl       varDecl;            // For the variable that we will create to hold our MethodHandle
    public Expr.FunDecl       owner;              // If we are nested inside another function then this the enclosing function

    public boolean            isWrapper;   // Whether this is the wrapper function or the real one
    public Expr.FunDecl       wrapper;     // The wrapper method that handles var arg and named arg invocations

    public boolean        isScriptMain = false; // Whether this is the funDecl for the script main function
    public Stmt.ClassDecl classDecl = null;     // For init methods this is our ClassDecl
    public int            closureCount = 0;
    public boolean        isCompiled = false;

    // Nested while loops. Used by Resolver to find target of break/continue stmts.
    public Deque<Stmt.While> whileLoops = new ArrayDeque<>();

    // Stack of blocks used during Resolver phase to track variables and which scope they
    // are declared in and used during Parser phase to track function declarations so we
    // can handle forward references during Resolver phase
    public Deque<Stmt.Block> blocks = new ArrayDeque<>();

    // Which heap locals from our parent we need passed in to us
    public LinkedHashMap<String,Expr.VarDecl>       heapLocalsByName = new LinkedHashMap<>();
    public LinkedHashMap<Expr.VarDecl,Expr.VarDecl> heapLocals       = new LinkedHashMap<>();

    public HashMap<String,Expr.VarDecl> globals = new HashMap<>();   // global vars accessed by this function

    // Remember earliest (in the code) forward reference to us so we can make sure that
    // no variables we close over are declared after that reference
    public Token earliestForwardReference;

    public boolean isClosure()    { return nameToken == null; }
    public boolean isStatic()     { return functionDescriptor.isStatic; }
    public boolean isInitMethod() { return functionDescriptor.isInitMethod; }
    public int     globalsVar()   { return isScriptMain ? (functionDescriptor.isAsync ? 2 : 1) : -1; }
    public FunDecl(Token startToken, Token nameToken, JactlType returnType, List<Stmt.VarDecl> parameters) {
      this.startToken = startToken;
      this.nameToken = nameToken;
      this.returnType = returnType;
      this.parameters = parameters;
      this.location = startToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitFunDecl(this); }
    @Override public String toString() { return "FunDecl[" + "startToken=" + startToken + ", " + "nameToken=" + nameToken + ", " + "returnType=" + returnType + ", " + "parameters=" + parameters + "]"; }
  }

  /**
   * When variable used as lvalue in an assignment
   */
  public static class VarAssign extends Expr implements ManagesResult {
    public Identifier identifierExpr;
    public Token      operator;
    public Expr       expr;
    public VarAssign(Identifier identifierExpr, Token operator, Expr expr) {
      this.identifierExpr = identifierExpr;
      this.operator = operator;
      this.expr = expr;
      this.location = operator;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitVarAssign(this); }
    @Override public String toString() { return "VarAssign[" + "identifierExpr=" + identifierExpr + ", " + "operator=" + operator + ", " + "expr=" + expr + "]"; }
  }

  /**
   * When variable used as lvalue in an assignment of type +=, -=, ...
   */
  public static class VarOpAssign extends Expr implements ManagesResult {
    public Identifier identifierExpr;
    public Token      operator;
    public Expr       expr;
    public VarOpAssign(Identifier identifierExpr, Token operator, Expr expr) {
      this.identifierExpr = identifierExpr;
      this.operator = operator;
      this.expr = expr;
      this.location = operator;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitVarOpAssign(this); }
    @Override public String toString() { return "VarOpAssign[" + "identifierExpr=" + identifierExpr + ", " + "operator=" + operator + ", " + "expr=" + expr + "]"; }
  }

  /**
   * Used to represent assignment to a field or list element
   */
  public static class FieldAssign extends Expr implements ManagesResult {
    public Expr  parent;
    public Token accessType;
    public Expr  field;
    public Token assignmentOperator;
    public Expr  expr;
    public FieldAssign(Expr parent, Token accessType, Expr field, Token assignmentOperator, Expr expr) {
      this.parent = parent;
      this.accessType = accessType;
      this.field = field;
      this.assignmentOperator = assignmentOperator;
      this.expr = expr;
      this.location = accessType;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitFieldAssign(this); }
    @Override public String toString() { return "FieldAssign[" + "parent=" + parent + ", " + "accessType=" + accessType + ", " + "field=" + field + ", " + "assignmentOperator=" + assignmentOperator + ", " + "expr=" + expr + "]"; }
  }

  /**
   * Used to represent assignment to a field or list element where assignment is done with
   * one of the +=, -=, *=, ... operations
   */
  public static class FieldOpAssign extends Expr implements ManagesResult {
    public Expr  parent;
    public Token accessType;
    public Expr  field;
    public Token assignmentOperator;
    public Expr  expr;

    // true if value before operation should be result - used for post inc/dec of fields
    // where we covert to a binary += or -= and then need the before value as the result
    public boolean isPreIncOrDec;
    public FieldOpAssign(Expr parent, Token accessType, Expr field, Token assignmentOperator, Expr expr) {
      this.parent = parent;
      this.accessType = accessType;
      this.field = field;
      this.assignmentOperator = assignmentOperator;
      this.expr = expr;
      this.location = accessType;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitFieldOpAssign(this); }
    @Override public String toString() { return "FieldOpAssign[" + "parent=" + parent + ", " + "accessType=" + accessType + ", " + "field=" + field + ", " + "assignmentOperator=" + assignmentOperator + ", " + "expr=" + expr + "]"; }
  }

  /**
   * Marker for when we need an Expr but we already have a value on the stack. This is used
   * for x += y type expressions which turn into x = _Noop_ + y where _Noop_ is used to mark
   * the place where the x value will be inserted into the binary expressions.
   */
  public static class Noop extends Expr {
    public Token operator;
    public Expr  originalExpr;      // When Noop used to replace initialiser for parameters this points to original initialiser (used in Intellij plugin)
    public Noop(Token operator) {
      this.operator = operator;
      this.location = operator;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitNoop(this); }
    @Override public String toString() { return "Noop[" + "operator=" + operator + "]"; }
  }

  /**
   * Closure definition
   */
  public static class Closure extends Expr implements ManagesResult {
    public Token        startToken;
    public Expr.FunDecl funDecl;
    public boolean      noParamsDefined;
    public boolean      closureIsBlock;  // True if closure turned out to just be a code block
    public Closure(Token startToken, Expr.FunDecl funDecl, boolean noParamsDefined) {
      this.startToken = startToken;
      this.funDecl = funDecl;
      this.noParamsDefined = noParamsDefined;
      this.location = startToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitClosure(this); }
    @Override public String toString() { return "Closure[" + "startToken=" + startToken + ", " + "funDecl=" + funDecl + ", " + "noParamsDefined=" + noParamsDefined + "]"; }
  }

  public static class Return extends Expr {
    public Token      returnToken;
    public Expr       expr;
    public JactlType returnType;      // Return type of the function we are embedded in
    public FunDecl    funDecl;
    public Return(Token returnToken, Expr expr, JactlType returnType) {
      this.returnToken = returnToken;
      this.expr = expr;
      this.returnType = returnType;
      this.location = returnToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitReturn(this); }
    @Override public String toString() { return "Return[" + "returnToken=" + returnToken + ", " + "expr=" + expr + ", " + "returnType=" + returnType + "]"; }
  }

  /**
   * Break statement
   */
  public static class Break extends Expr {
    public Token breakToken;
    public Token label;
    public Stmt.While whileLoop;
    public Break(Token breakToken, Token label) {
      this.breakToken = breakToken;
      this.label = label;
      this.location = breakToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitBreak(this); }
    @Override public String toString() { return "Break[" + "breakToken=" + breakToken + ", " + "label=" + label + "]"; }
  }

  /**
   * Continue statement
   */
  public static class Continue extends Expr{
    public Token continueToken;
    public Token label;
    public Stmt.While whileLoop;
    public Continue(Token continueToken, Token label) {
      this.continueToken = continueToken;
      this.label = label;
      this.location = continueToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitContinue(this); }
    @Override public String toString() { return "Continue[" + "continueToken=" + continueToken + ", " + "label=" + label + "]"; }
  }

  public static class Print extends Expr {
    public Token printToken;
    public Expr  expr;
    public boolean newLine;    // Whether to print newline
    public Print(Token printToken, Expr expr, boolean newLine) {
      this.printToken = printToken;
      this.expr = expr;
      this.newLine = newLine;
      this.location = printToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitPrint(this); }
    @Override public String toString() { return "Print[" + "printToken=" + printToken + ", " + "expr=" + expr + ", " + "newLine=" + newLine + "]"; }
  }

  public static class Die extends Expr {
    public Token dieToken;
    public Expr  expr;
    public Die(Token dieToken, Expr expr) {
      this.dieToken = dieToken;
      this.expr = expr;
      this.location = dieToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitDie(this); }
    @Override public String toString() { return "Die[" + "dieToken=" + dieToken + ", " + "expr=" + expr + "]"; }
  }

  public static class Eval extends Expr {
    public Token evalToken;
    public Expr  script;
    public Expr  globals;
    public Eval(Token evalToken, Expr script, Expr globals) {
      this.evalToken = evalToken;
      this.script = script;
      this.globals = globals;
      this.location = evalToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitEval(this); }
    @Override public String toString() { return "Eval[" + "evalToken=" + evalToken + ", " + "script=" + script + ", " + "globals=" + globals + "]"; }
  }

  /**
   * Used to turn a list of statements into an expression so that we can support "do {...}":
   *   x == max or do { x++; y-- } and return x + y;
   */
  public static class Block extends Expr {
    public Token      token;
    public Stmt.Block block;
    public Block(Token token, Stmt.Block block) {
      this.token = token;
      this.block = block;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitBlock(this); }
    @Override public String toString() { return "Block[" + "token=" + token + ", " + "block=" + block + "]"; }
  }

  /**
   * Switch statement
   */
  public static class Switch extends Expr {
    public Token            matchToken;
    public Expr             subject;
    public List<SwitchCase> cases;
    public Expr             defaultCase;
    public VarDecl          itVar;
    public Stmt.Block       block;     // Need a block for tracking it var
    public Switch(Token matchToken, Expr subject, List<SwitchCase> cases, Expr defaultCase) {
      this.matchToken = matchToken;
      this.subject = subject;
      this.cases = cases;
      this.defaultCase = defaultCase;
      this.location = matchToken;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitSwitch(this); }
    @Override public String toString() { return "Switch[" + "matchToken=" + matchToken + ", " + "subject=" + subject + ", " + "cases=" + cases + ", " + "defaultCase=" + defaultCase + "]"; }
  }

  public static class SwitchCase extends Expr {
    public List<Pair<Expr,Expr>> patterns;        // List of pairs of pattern/ifExpression
    public Expr                  result;
    public Stmt.Block            block;          // Need a block for captured regex and destructured vars
    public Expr                  switchSubject;  // Need to know type of switch expression for binding variables
    public SwitchCase(List<Pair<Expr,Expr>> patterns, Expr result) {
      this.patterns = patterns;
      this.result = result;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitSwitchCase(this); }
    @Override public String toString() { return "SwitchCase[" + "patterns=" + patterns + ", " + "result=" + result + "]"; }
  }

  /**
   * For use in constructor pattern.
   * Can be named or not:
   *   X(1,2,[_,_,a])
   *   X(i:1,j:2,list:[_,_,a])
   */
  public static class ConstructorPattern extends Expr {
    public Token      token;
    public TypeExpr   typeExpr;
    public Expr       args;
    public ConstructorPattern(Token token, TypeExpr typeExpr, Expr args) {
      this.token = token;
      this.typeExpr = typeExpr;
      this.args = args;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitConstructorPattern(this); }
    @Override public String toString() { return "ConstructorPattern[" + "token=" + token + ", " + "typeExpr=" + typeExpr + ", " + "args=" + args + "]"; }
  }

  /**
   * Expr for wrapping a type. Used for instanceof, !instanceof, and as
   */
  public static class TypeExpr extends Expr {
    public Token      token;
    public JactlType typeVal;
    public TypeExpr(Token token, JactlType typeVal) {
      this.token = token;
      this.typeVal = typeVal;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitTypeExpr(this); }
    @Override public String toString() { return "TypeExpr[" + "token=" + token + ", " + "typeVal=" + typeVal + "]"; }
  }

  /**
   * Comma-separated list of expressions in parentheses.
   * Used for multi-assignments: (x,y,z) = [1,2,3]
   * Only used within Parser at the moment (unless we eventually support comma as an operator)
   */
  public static class ExprList extends Expr {
    public Token      token;
    public List<Expr> exprs;
    public ExprList(Token token, List<Expr> exprs) {
      this.token = token;
      this.exprs = exprs;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitExprList(this); }
    @Override public String toString() { return "ExprList[" + "token=" + token + ", " + "exprs=" + exprs + "]"; }
  }

  ////////////////////////////////////////////////////////////////////

  // = Used when generating wrapper method

  /**
   * Array length
   */
  public static class ArrayLength extends Expr implements ManagesResult {
    public Token token;
    public Expr array;
    public ArrayLength(Token token, Expr array) {
      this.token = token;
      this.array = array;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitArrayLength(this); }
    @Override public String toString() { return "ArrayLength[" + "token=" + token + ", " + "array=" + array + "]"; }
  }

  /**
   * Array get
   */
  public static class ArrayGet extends Expr implements ManagesResult {
    public Token token;
    public Expr  array;
    public Expr  index;
    public ArrayGet(Token token, Expr array, Expr index) {
      this.token = token;
      this.array = array;
      this.index = index;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitArrayGet(this); }
    @Override public String toString() { return "ArrayGet[" + "token=" + token + ", " + "array=" + array + ", " + "index=" + index + "]"; }
  }

  /**
   * LoadParamValue - load value needed for a param.
   * Can be HeapLocal if isPassedAsHeapLocal is set or just a standard value.
   */
  public static class LoadParamValue extends Expr implements ManagesResult {
    public Token name;
    public Expr.VarDecl paramDecl;
    public Expr.VarDecl varDecl;
    public LoadParamValue(Token name, Expr.VarDecl paramDecl) {
      this.name = name;
      this.paramDecl = paramDecl;
      this.location = name;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitLoadParamValue(this); }
    @Override public String toString() { return "LoadParamValue[" + "name=" + name + ", " + "paramDecl=" + paramDecl + "]"; }
  }

  /**
   * Invoke a user function - used for invoking actual function at end of varargs wrapper function
   */
  public static class InvokeFunDecl extends Expr implements ManagesResult {
    public Token        token;
    public Expr.FunDecl funDecl;
    public List<Expr>   args;
    public InvokeFunDecl(Token token, Expr.FunDecl funDecl, List<Expr> args) {
      this.token = token;
      this.funDecl = funDecl;
      this.args = args;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitInvokeFunDecl(this); }
    @Override public String toString() { return "InvokeFunDecl[" + "token=" + token + ", " + "funDecl=" + funDecl + ", " + "args=" + args + "]"; }
  }

  /**
   * Invoke init method of a class
   */
  public static class InvokeInit extends Expr {
    public Token            token;
    // Whether to use INVOKESPECIAL or INVOKEVIRTUAL. INVOKESPECIAL needed when invoking super.method().
    public boolean          invokeSpecial;
    public ClassDescriptor  classDescriptor;
    public List<Expr>       args;
    public InvokeInit(Token token, boolean invokeSpecial, ClassDescriptor classDescriptor, List<Expr> args) {
      this.token = token;
      this.invokeSpecial = invokeSpecial;
      this.classDescriptor = classDescriptor;
      this.args = args;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitInvokeInit(this); }
    @Override public String toString() { return "InvokeInit[" + "token=" + token + ", " + "invokeSpecial=" + invokeSpecial + ", " + "classDescriptor=" + classDescriptor + ", " + "args=" + args + "]"; }
  }

  /**
   * Invoke an internal utility function
   */
  public static class InvokeUtility extends Expr {
    public Token       token;
    public Class       clss;
    public String      methodName;
    public List<Class> paramTypes;
    public List<Expr>  args;
    public InvokeUtility(Token token, Class clss, String methodName, List<Class> paramTypes, List<Expr> args) {
      this.token = token;
      this.clss = clss;
      this.methodName = methodName;
      this.paramTypes = paramTypes;
      this.args = args;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitInvokeUtility(this); }
    @Override public String toString() { return "InvokeUtility[" + "token=" + token + ", " + "clss=" + clss + ", " + "methodName=" + methodName + ", " + "paramTypes=" + paramTypes + ", " + "args=" + args + "]"; }
  }

  /**
   * Create a new instance of a class
   */
  public static class InvokeNew extends Expr {
    public Token      token;
    public JactlType  instanceType;
    public List<Expr> dimensions = new ArrayList<>();
    public InvokeNew(Token token, JactlType instanceType) {
      this.token = token;
      this.instanceType = instanceType;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitInvokeNew(this); }
    @Override public String toString() { return "InvokeNew[" + "token=" + token + ", " + "instanceType=" + instanceType + "]"; }
  }

  /**
   * Load default value of given type onto stack
   */
  public static class DefaultValue extends Expr {
    public Token      token;
    public JactlType varType;
    public DefaultValue(Token token, JactlType varType) {
      this.token = token;
      this.varType = varType;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitDefaultValue(this); }
    @Override public String toString() { return "DefaultValue[" + "token=" + token + ", " + "varType=" + varType + "]"; }
  }

  /**
   * For situations where we know the class name up front and don't want to have to create
   * a new JactlType value for it.
   */
  public static class InstanceOf extends Expr {
    public Token  token;
    public Expr   expr;      // The object for which we are checking the type
    public String className; // The internal class name to check for
    public InstanceOf(Token token, Expr expr, String className) {
      this.token = token;
      this.expr = expr;
      this.className = className;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitInstanceOf(this); }
    @Override public String toString() { return "InstanceOf[" + "token=" + token + ", " + "expr=" + expr + ", " + "className=" + className + "]"; }
  }

  /**
   * Cast to given type
   */
  public static class CheckCast extends Expr {
    public Token      token;
    public Expr       expr;      // Object being cast
    public JactlType castType;  // Type to cast to
    public CheckCast(Token token, Expr expr, JactlType castType) {
      this.token = token;
      this.expr = expr;
      this.castType = castType;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitCheckCast(this); }
    @Override public String toString() { return "CheckCast[" + "token=" + token + ", " + "expr=" + expr + ", " + "castType=" + castType + "]"; }
  }

  /**
   * Used in init method to convert an expression into a user instance type. If the expression
   * is not the right type but is a Map/List we invoke the constructor to convert into the right
   * instance type.
   */
  public static class ConvertTo extends Expr {
    public Token      token;
    public JactlType varType;
    public Expr       expr;
    public Expr       source;
    public Expr       offset;
    public ConvertTo(Token token, JactlType varType, Expr expr, Expr source, Expr offset) {
      this.token = token;
      this.varType = varType;
      this.expr = expr;
      this.source = source;
      this.offset = offset;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitConvertTo(this); }
    @Override public String toString() { return "ConvertTo[" + "token=" + token + ", " + "varType=" + varType + ", " + "expr=" + expr + ", " + "source=" + source + ", " + "offset=" + offset + "]"; }
  }

  /**
   * Used for times when we need to get the source or offset value from our params (when needsLocation is set).
   * Since we don't declare formal parameters for these we use this as a special place holder.
   */
  public static class SpecialVar extends Expr {
    public Token   name;          // $source or $offset (Utils.SOURCE_VAR_NAME, Utils.OFFSET_VAR_NAME)
    public FunDecl function;     // Our current function
    public SpecialVar(Token name) {
      this.name = name;
      this.location = name;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitSpecialVar(this); }
    @Override public String toString() { return "SpecialVar[" + "name=" + name + "]"; }
  }

  /**
   * Cast existing stack value (used in Match expression to convert results to the right type)
   */
  public static class StackCast extends Expr {
    public Token     token;
    public JactlType castType;
    public StackCast(Token token, JactlType castType) {
      this.token = token;
      this.castType = castType;
      this.location = token;
    }
    @Override public <T> T accept(Visitor<T> visitor) { return visitor.visitStackCast(this); }
    @Override public String toString() { return "StackCast[" + "token=" + token + ", " + "castType=" + castType + "]"; }
  }

  public interface Visitor<T> {
    T visitBinary(Binary expr);
    T visitRegexMatch(RegexMatch expr);
    T visitRegexSubst(RegexSubst expr);
    T visitTernary(Ternary expr);
    T visitPrefixUnary(PrefixUnary expr);
    T visitPostfixUnary(PostfixUnary expr);
    T visitCast(Cast expr);
    T visitCall(Call expr);
    T visitMethodCall(MethodCall expr);
    T visitLiteral(Literal expr);
    T visitListLiteral(ListLiteral expr);
    T visitMapLiteral(MapLiteral expr);
    T visitIdentifier(Identifier expr);
    T visitClassPath(ClassPath expr);
    T visitExprString(ExprString expr);
    T visitVarDecl(VarDecl expr);
    T visitFunDecl(FunDecl expr);
    T visitVarAssign(VarAssign expr);
    T visitVarOpAssign(VarOpAssign expr);
    T visitFieldAssign(FieldAssign expr);
    T visitFieldOpAssign(FieldOpAssign expr);
    T visitNoop(Noop expr);
    T visitClosure(Closure expr);
    T visitReturn(Return expr);
    T visitBreak(Break expr);
    T visitContinue(Continue expr);
    T visitPrint(Print expr);
    T visitDie(Die expr);
    T visitEval(Eval expr);
    T visitBlock(Block expr);
    T visitSwitch(Switch expr);
    T visitSwitchCase(SwitchCase expr);
    T visitConstructorPattern(ConstructorPattern expr);
    T visitTypeExpr(TypeExpr expr);
    T visitExprList(ExprList expr);
    T visitArrayLength(ArrayLength expr);
    T visitArrayGet(ArrayGet expr);
    T visitLoadParamValue(LoadParamValue expr);
    T visitInvokeFunDecl(InvokeFunDecl expr);
    T visitInvokeInit(InvokeInit expr);
    T visitInvokeUtility(InvokeUtility expr);
    T visitInvokeNew(InvokeNew expr);
    T visitDefaultValue(DefaultValue expr);
    T visitInstanceOf(InstanceOf expr);
    T visitCheckCast(CheckCast expr);
    T visitConvertTo(ConvertTo expr);
    T visitSpecialVar(SpecialVar expr);
    T visitStackCast(StackCast expr);
  }
}
